### PR TITLE
Add toggle playback mode button in the player.

### PR DESCRIPTION
**Pull request by andylow**

### CODE REVIEW

**Comment by lyswhut** [comment]
Thank you for the PR, but this feature has been marked as [enhanced](https://github.com/lyswhut/lx-music-desktop/issues/174), and I have completed the development, now I am waiting for others to design the icon ...😂
Now I need the following icons:

- Desktop lyrics
  - **Turn on**
  - **Turn off**
- Play mode switch
  - **List play**
  - **List loop**
  - **Random list**
  - **Single loop**
  - **Disable**(disable automatic switching to the next song)
- **Add the currently playing song to**

A total of eight icons, can you provide me with the rest of the icons? Or later I will wait for others to design the icon, and then push the code to GitHub to release a new version

**Comment by andylow** [comment]
I see, good to know that. 
Except the 4 icons there, I also have 3 more icons here, you can check it out whether there are suitable to use.
[svg-icons.zip](https://github.com/lyswhut/lx-music-desktop/files/5239737/svg-icons.zip)

However, I'm not sure what is "Add the currently playing song to".

**Comment by lyswhut** [comment]
Thank you very much for the icon!
"Add the currently playing song to" is to add the currently playing song to my list. 

I have now changed the lyrics icon to line style, This is what it looks like after rendering:
image

**Comment by andylow** [comment]
Awesome ! 👏🏻
I will close this PR :)

**Pull request closed without merging**
